package io.github.sweehaw.audit.enums;

/**
 * @author sweehaw
 */
public enum AuditAction {
    /**
     *
     */
    USER,
    USER_ACCESS_URL,
    USER_ACCESS_IP,
    USER_ACCESS_BROWSER,
    USER_ACCESS_ID,
    USER_ACCESS_DATE,
    USER_ACCESS_SERVLET,
    USER_ACCESS_RANDOM_STRING,
    USER_ACCESS_PK,
    USER_ACCESS_PK_VALUE,
    USER_ACCESS_ACTION,
    USER_ACCESS_ENTITY,
    USER_ACCESS_SERVICE,
    USER_ACCESS_ACTION_ID,
    USER_ACCESS_FIELD,
    USER_ACCESS_OLD_VALUE,
    USER_ACCESS_NEW_VALUE
}
